import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "./react-query-client";
import NoSSR from "./components/NoSSR";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <>
            {children}
            <NoSSR>
              <ReactQueryDevtools
                initialIsOpen={false}
                position="right"
              ></ReactQueryDevtools>
            </NoSSR>
          </>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
